- OWNERS
The OWNERS file is for prow only. See https://www.kubernetes.dev/docs/guide/owners/ for more.
> chore: create OWNERS

- i18n/zh-Hans/code.json
- i18n/zh-Hans/docusaurus-plugin-content-docs/current.json
- i18n/zh-Hans/docusaurus-plugin-content-docs/version-1.5.1.json
- sidebars.js
- versioned_sidebars/version-1.5.1-sidebars.json
移除腾讯云开发者实验室的链接。目前 https://cloud.tencent.com/lab/labslist 已经改版，并且不知道为何 Halo 的实验教程已经被删除，所以在文档移除这个链接。
> docs: remove tencent developer labs sidebar link

- .markdownlint.json
- docs/getting-started/install/other/docker-compose.md
- versioned_docs/version-1.5.2/getting-started/install/other/docker-compose.md
优化使用 Docker Compose 部署 Halo 的文档，主要以下几个改动：
1. 使用单独的文件夹托管数据和 docker-compose.yaml 文件。
2. 使用 Docker 环境变量代替通过 application.yaml 文件来配置。
3. 修改使用 MySQL 镜像时，创建数据库的方式。
4. 新增仅使用 Halo + MySQL 的配置。
已经对三种情况做了创建，更新，销毁，重建的测试。如果大家的电脑为 arm 架构的 CPU，可以将 MySQL 的镜像改为 `mariadb:latest` 进行测试。
/cc @halo-dev/sig-docs @halo-dev/sig-infra
> docs: improve docker compose documentations

- docs/contribution/pr.md
- versioned_docs/version-1.5.2/contribution/pr.md
See https://github.com/halo-dev/halo/pull/1890 for more.
Fix #76 
/cc @halo-dev/sig-docs
> Refine pr.md to be clearer

- docs/getting-started/install/other/docker-compose.md
- versioned_docs/version-1.5.4/getting-started/install/other/docker-compose.md
Fixes halo-dev/halo#2257
see https://hub.docker.com/_/mysql
```release-note
None
```
> fix: docker-compose documentation about the mysql container configurations

- docs/getting-started/prepare.md
- versioned_docs/version-1.5.4/getting-started/prepare.md
添加不能将 Halo 反向代理到域名子目录的提示。
```release-note
None
```
> docs: add a tip that cannot map halo to a domain subfolder

- docs/getting-started/install/docker.md
/kind bug
原始的 Docker 运行命令无法在 zsh 下正常执行：
```bash
╰─❯ docker run \
-it -d \
--name halo-next \
-p 8090:8090 \
-v ~/halo-next:/root/halo-next \
-e HALO_EXTERNAL_URL=http://localhost:8090/ \ # 请修改外部访问链接
-e HALO_SECURITY_INITIALIZER_SUPERADMINPASSWORD=P@88w0rd \ # 请修改管理员密码
-e HALO_EXTERNAL_URL=http://localhost:8090/ \
-e HALO_SECURITY_INITIALIZER_SUPERADMINPASSWORD=P@88w0rd \
halohub/halo-dev:2.0.0-alpha.1
docker: invalid reference format.
See 'docker run --help'.
zsh: command not found: -e
zsh: command not found: -e
```
去掉注释部分可正常执行：
```bash
╰─❯ docker run \
-it -d \
--name halo-next \
-p 8090:8090 \
-v ~/halo-next:/root/halo-next \
-e HALO_EXTERNAL_URL=http://localhost:8090/ \
-e HALO_SECURITY_INITIALIZER_SUPERADMINPASSWORD=P@88w0rd \
halohub/halo-dev:2.0.0-alpha.1 …
```
> Rectify docker running command

- docs/getting-started/downloads.md
- versioned_docs/version-1.4/getting-started/downloads.md
- versioned_docs/version-1.5/getting-started/downloads.md
- versioned_docs/version-1.6/getting-started/downloads.md
Change mirror site frontend website to new address, shouldn't affect old download link such as `https://dl.halo.run/release/halo-1.3.0.jar`
Related post: https://nova.moe/halo-mirror-serverless/
Related repo: https://github.com/halo-sigs/halo-dl-api
```release-note
None
```
> Change mirror frontend URL from https://dl.halo.run to https://download.halo.run

- docs/developer-guide/theme/prepare.md
在主题开发文档中添加配置模板引擎缓存的提示。
```release-note
None
```
> docs: tips for configuring template caching for theme development

- docs/getting-started/install/docker-compose.md
add PGUSER to fix `FATAL: role "root" does not exist` warning.
```release-note
None
```
> docs: update docker-compose.md for PostgreSQL PGUSER env

- docs/developer-guide/core/run.md
- versioned_docs/version-2.0/developer-guide/core/run.md
- versioned_docs/version-2.1/developer-guide/core/run.md
- versioned_docs/version-2.2/developer-guide/core/run.md
在开发环境文档中添加 Console 代理的提示。
```release-note
None
```
> docs: add tips of console proxy

- docs/getting-started/install/docker-compose.md
- versioned_docs/version-2.2/getting-started/install/docker-compose.md
在 Docker Compose 文件中，使用 `/actuator/health/readiness` 接口为 Halo 服务增加健康检查。
```release-note
docs: add healthcheck for halo in compose
```
> docs: add healthcheck for halo in compose

- docs/developer-guide/core/run.md
- versioned_docs/version-2.0/developer-guide/core/run.md
- versioned_docs/version-2.1/developer-guide/core/run.md
- versioned_docs/version-2.2/developer-guide/core/run.md
添加开发环境下初始管理员用户名和密码的提示
Fixes #188 
```release-note
None
```
> docs:  add a tip for default admin username and password for development environment

- docs/getting-started/install/docker-compose.md
- versioned_docs/version-2.2/getting-started/install/docker-compose.md
修复由 https://github.com/halo-dev/docs/pull/189 导致的 Docker Compose 代码块高亮行错误的问题。
before:
after:
```release-note
None
```
> fix: incorrect hightlight number of docker compose example code block

- docs/developer-guide/core/build.md
- docs/developer-guide/core/run.md
因为目前已经将 Console 合并到了 Halo 主仓库，所以需要修改开发环境运行和构建的文档。
See https://github.com/halo-dev/halo/issues/3393
Fixes #197 
```release-note
None
```
> docs: update documentations for building and running in development env

- docs/developer-guide/plugin/hello-world.md
- docs/developer-guide/plugin/runtime-mode.md
- versioned_docs/version-2.5/developer-guide/plugin/hello-world.md
- versioned_docs/version-2.5/developer-guide/plugin/runtime-mode.md
Halo 插件开发 Windows 环境下插件绝对路径的补充
Ref #218 
```release-note
None
```
> docs: add configuration examples for the Windows platform in the plugin-related documents

- docusaurus.config.js
- i18n/zh-Hans/code.json
- i18n/zh-Hans/docusaurus-theme-classic/footer.json
- i18n/zh-Hans/docusaurus-theme-classic/navbar.json
1. 修改标题为 `Halo 文档`。
2. Sitemap 排除旧文档的索引，防止 Algolia 额度不够导致无法建索引。
3. 修改页面底部的 Copyright。
4. 修改底部的主题仓库为应用市场。
```release-note
None
```
> chore: update site configs

- docs/getting-started/first-post.md
- docs/getting-started/install/docker-compose.md
- docs/getting-started/install/docker.md
- docs/getting-started/install/other/traefik.md
- docs/getting-started/install/slots/docker-args.md
更新部署文档，移除通过参数的形式设置初始管理员。
Fixes #241 
```release-note
None 
```
> docs: update the instructions for the initial administrator in the deployment document

- docs/getting-started/install/docker-compose.md
使用caching_sha2_password代替mysql_native_password。
以解决使用My SQL的Docker镜像报Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'。告警的问题。
```release-note
None
```
> Update MySQL to 8.1.0 to prevent mysql_native_password warning

- docs/developer-guide/theme/annotations.md
- docs/developer-guide/theme/finder-apis/menu.md
- versioned_docs/version-2.0/developer-guide/theme/finder-apis/menu.md
- versioned_docs/version-2.1/developer-guide/theme/annotations.md
- versioned_docs/version-2.1/developer-guide/theme/finder-apis/menu.md
- versioned_docs/version-2.2/developer-guide/theme/annotations.md
- versioned_docs/version-2.2/developer-guide/theme/finder-apis/menu.md
- versioned_docs/version-2.3/developer-guide/theme/annotations.md
- versioned_docs/version-2.3/developer-guide/theme/finder-apis/menu.md
- versioned_docs/version-2.4/developer-guide/theme/annotations.md
- versioned_docs/version-2.4/developer-guide/theme/finder-apis/menu.md
- versioned_docs/version-2.5/developer-guide/theme/annotations.md
- versioned_docs/version-2.5/developer-guide/theme/finder-apis/menu.md
- versioned_docs/version-2.6/developer-guide/theme/annotations.md
- versioned_docs/version-2.6/developer-guide/theme/finder-apis/menu.md
- versioned_docs/version-2.7/developer-guide/theme/annotations.md
- versioned_docs/version-2.7/developer-guide/theme/finder-apis/menu.md
- versioned_docs/version-2.8/developer-guide/theme/annotations.md
- versioned_docs/version-2.8/developer-guide/theme/finder-apis/menu.md
日常主题开发中，我们应该使用菜单最终生成到名字
```release-note
None
````
> fix: menu api example in theme dev docs

- docs/getting-started/install/docker-compose.md
- versioned_docs/version-2.0/getting-started/install/docker-compose.md
- versioned_docs/version-2.1/getting-started/install/docker-compose.md
- versioned_docs/version-2.2/getting-started/install/docker-compose.md
- versioned_docs/version-2.3/getting-started/install/docker-compose.md
- versioned_docs/version-2.4/getting-started/install/docker-compose.md
- versioned_docs/version-2.5/getting-started/install/docker-compose.md
- versioned_docs/version-2.6/getting-started/install/docker-compose.md
- versioned_docs/version-2.7/getting-started/install/docker-compose.md
- versioned_docs/version-2.8/getting-started/install/docker-compose.md
- versioned_docs/version-2.9/getting-started/install/docker-compose.md
固定 Docker Compose 文档中 postgres 的版本，防止使用 latest 标签导致跨版本不兼容。
```release-note
None
```
> docs: lock postgres version in docker compose example

- versioned_docs/version-2.9/developer-guide/theme/annotations.md
Fixes https://github.com/halo-dev/docs/issues/259
```release-note
修正文档中关于获取菜单显示名称的代码示例，详情请参见：https://github.com/halo-dev/docs/issues/259
```
> fix: example code in menu finder api

- docs/getting-started/install/podman.md
- sidebars.js
- versioned_docs/version-2.9/getting-started/install/podman.md
- versioned_sidebars/version-2.9-sidebars.json
添加使用 Podman 部署Halo的方法.
```release-note
None 
```
> docs: add halo on podman

- docs/getting-started/install/docker-compose.md
- docs/getting-started/install/other/traefik.md
目前 Halo 容器挂载目录配置 `./:/root/.halo2` 容易让用户无意在 Halo 工作目录添加一些其他无关目录，例如：Nginx 也挂载到当前目录。这可能会导致无法正常使用备份功能。目前也无法预知未来可能会发生什么样的错误。
Fixes https://github.com/halo-dev/halo/issues/4637
```release-note
修改 Halo 容器工作目录挂载目标目录为 ./halo2
```
> Change mount dir of Halo container to ./halo2

- docs/getting-started/install/docker-compose.md
- docs/getting-started/install/docker.md
- docs/getting-started/install/podman.md
- versioned_docs/version-2.10/getting-started/install/docker-compose.md
- versioned_docs/version-2.10/getting-started/install/docker.md
- versioned_docs/version-2.10/getting-started/install/podman.md
优化版本升级的备份说明，统一改为使用系统提供的备份功能，而不是手动操作工作目录。
```release-note
None
```
> docs: improve backup instructions in upgrade documentations

- docs/getting-started/install/jar-file.md
- versioned_docs/version-2.12/getting-started/install/jar-file.md
修改 Jar 文件部署文档，补充配置文件位置的参数说明。
Ref https://github.com/halo-dev/halo/issues/5259#issuecomment-1925783729
```release-note
None
```
> fix: missing config location attribute in jar document

- docs/getting-started/install/jar-file.md
- versioned_docs/version-2.12/getting-started/install/jar-file.md
在 https://github.com/halo-dev/docs/pull/309 中，修改配置挂载方式之后没有删除以前的提示。
```release-note
None
```
> docs: remove unnecessary tips

- docs/developer-guide/theme/prepare.md
- versioned_docs/version-2.0/developer-guide/theme/prepare.md
- versioned_docs/version-2.1/developer-guide/theme/prepare.md
- versioned_docs/version-2.10/developer-guide/theme/prepare.md
- versioned_docs/version-2.11/developer-guide/theme/prepare.md
- versioned_docs/version-2.12/developer-guide/theme/prepare.md
- versioned_docs/version-2.2/developer-guide/theme/prepare.md
- versioned_docs/version-2.3/developer-guide/theme/prepare.md
- versioned_docs/version-2.4/developer-guide/theme/prepare.md
- versioned_docs/version-2.5/developer-guide/theme/prepare.md
- versioned_docs/version-2.6/developer-guide/theme/prepare.md
- versioned_docs/version-2.7/developer-guide/theme/prepare.md
- versioned_docs/version-2.8/developer-guide/theme/prepare.md
- versioned_docs/version-2.9/developer-guide/theme/prepare.md
目前 https://github.com/halo-sigs/theme-astro-starter 还处于验证阶段，放置在文档中可能会造成一定困惑。
```release-note
None
```
> docs: remove theme-astro-starter template

- docs/developer-guide/annotations-form.md
- versioned_docs/version-2.1/developer-guide/annotations-form.md
- versioned_docs/version-2.10/developer-guide/annotations-form.md
- versioned_docs/version-2.11/developer-guide/annotations-form.md
- versioned_docs/version-2.12/developer-guide/annotations-form.md
- versioned_docs/version-2.2/developer-guide/annotations-form.md
- versioned_docs/version-2.3/developer-guide/annotations-form.md
- versioned_docs/version-2.4/developer-guide/annotations-form.md
- versioned_docs/version-2.5/developer-guide/annotations-form.md
- versioned_docs/version-2.6/developer-guide/annotations-form.md
- versioned_docs/version-2.7/developer-guide/annotations-form.md
- versioned_docs/version-2.8/developer-guide/annotations-form.md
- versioned_docs/version-2.9/developer-guide/annotations-form.md
修改《元数据表单定义》文档中关于 metadata.name 的描述。
Fixes https://github.com/halo-dev/docs/issues/298
```release-note
None
```
> docs: refine documentation for annotation setting name

- docs/developer-guide/plugin/api-reference/ui/extension-points/editor-create.md
为编辑器扩展添加 title 字段的描述，为 https://github.com/halo-dev/halo/pull/5465 的改动添加文档。
```release-note
None
```
> docs: add title prop for editor create extension point

- docs/developer-guide/plugin/api-reference/ui/extension-points/default-editor-extension-create.md
将 selection 属性添加至默认编辑器的 handleDrop 扩展中。相关改动查看 https://github.com/halo-dev/halo/pull/5570
```release-note
None
```
> docs: add the selection attribute to handleDrop

- docs/getting-started/install/slots/docker-args.md
- versioned_docs/version-2.14/getting-started/install/slots/docker-args.md
根据 https://github.com/halo-dev/halo/issues/5534#issuecomment-2011499798 中提到的，临时将文档中 MariaDB 的数据库连接地址修改为使用 mysql 驱动。
```release-note
None
```
> docs: update r2dbc url for MariaDB

- i18n/zh-Hans/code.json
- i18n/zh-Hans/docusaurus-plugin-content-docs/current.json
重新生成翻译文件，在 https://github.com/halo-dev/docs/pull/345 中遗漏了重新生成翻译文件的步骤。
/kind documentaion
```release-note
None
```
> fix: translations

- docs/developer-guide/theme/template-tag.md
- versioned_docs/version-2.15/developer-guide/theme/template-tag.md
移除文档中关于 `halo:comment` 标签的 colorScheme 字段，这是以前的设计错误，此模板引擎标签不应该涉及最终 UI 相关的功能。目前官方的评论插件已经支持通过 CSS 变量来改变配色和其他样式。
```release-note
None
```
> docs: remove colorScheme param for halo:comment tag

- docusaurus.config.js
- package.json
- pnpm-lock.yaml
引入 esbuild，提升构建速度。
before:
after:
```release-note
None
```
> chore: use esbuild instead of babel

- docusaurus.config.js
- package.json
- pnpm-lock.yaml
使用 swc 代替 esbuild，之前在 https://github.com/halo-dev/docs/pull/358 中引入了 esbuild，但发现在生产构建之后会出现这个问题：
暂时不清楚为什么，使用 swc 测试构建之后没有这个问题。
/kind bug
```release-note
None
```
> chore: use swc instead of esbuild

- docs/getting-started/install/slots/_docker-args.md
使用 MariaDB 原生驱动无法启动的问题将在 https://github.com/halo-dev/halo/pull/6133 中修复，并发布到 2.17.0，所以移除此提示。
```release-note
None
```
> docs: remove tips related to mariadb driver

- docs/developer-guide/form-schema.md
增加 formkit list 的文档。
```release-note
None
```
> docs: add dynamic list doc

- docs/developer-guide/plugin/api-reference/server/setting-fetcher.md
- sidebars.js
新增关于如何使用插件配置的文档
see also https://github.com/halo-dev/halo/pull/6141
```release-note
None
```
> docs: add detailed guide on how to use plugin settings

- docs/developer-guide/plugin/api-reference/server/reconciler.md
补充关于定制和构建控制器的文档
see also https://github.com/halo-dev/halo/pull/6145
```release-note
None
```
> docs: add guide for customize and build controller

- docs/getting-started/install/podman.md
- docs/getting-started/install/slots/_docker-args.md
移除部署文章的 `halo.cache.page.disabled` 参数，在 2.17 中已经[移除此功能](https://github.com/halo-dev/halo/pull/6108)，后续将由 https://github.com/halo-sigs/plugin-page-cache 提供此功能。
```release-note
None
```
> docs: remove halo.cache.page.disabled arg

- docs/developer-guide/plugin/api-reference/ui/api-request.md
- sidebars.js
为插件提供 api-client 的使用文档。
```release-note
None
```
> docs: add api client usage docs for plugin

- docs/developer-guide/plugin/examples/todolist.md
- versioned_docs/version-2.17/developer-guide/plugin/examples/todolist.md
移除已经过时的 PluginWrapper 引用
```release-note
None
```
> chore: remove deprecated plugin wrapper

- docs/developer-guide/plugin/api-reference/server/extension-points/template-footer-processor.md
- sidebars.js
- versioned_docs/version-2.17/developer-guide/plugin/api-reference/server/extension-points/template-footer-processor.md
- versioned_sidebars/version-2.17-sidebars.json
为 TemplateFooterProcessor 添加开发文档
see also https://github.com/halo-dev/halo/pull/6191
```release-note
None
```
> docs: add docs for template footer processor

- docs/developer-guide/plugin/api-reference/server/login-handler-enhancer.md
- sidebars.js
- versioned_docs/version-2.17/developer-guide/plugin/api-reference/server/login-handler-enhancer.md
- versioned_sidebars/version-2.17-sidebars.json
增加关于 LoginHandlerEnhancer 的使用文档
see also https://github.com/halo-dev/halo/pull/6176
```release-note
None
```
> docs: add docs for login handler enhancer

- docs/developer-guide/theme/finder-apis/category.md
- versioned_docs/version-2.17/developer-guide/theme/finder-apis/category.md
为分类 Finder API 新增的 getBreadcrumbs 方法提供文档
see also https://github.com/halo-dev/halo/pull/6135
```release-note
None
```
> docs: add docs for getBreadcrumbs of category finder

- docs/developer-guide/theme/finder-apis/post.md
- versioned_docs/version-2.18/developer-guide/theme/finder-apis/post.md
补充根据创建者用户名和分页参数获取文章列表。
```release-note
None
```
> docs: refine docs for postFinder.listByOwner

- docs/getting-started/install/docker-compose.md
- docs/getting-started/install/slots/_docker-args.md
- i18n/zh-Hans/code.json
- versioned_docs/version-2.18/getting-started/install/docker-compose.md
- versioned_docs/version-2.18/getting-started/install/slots/_docker-args.md
优化 Docker Compose 部署文档的篇幅，使用选项卡展示不同的配置示例。
```release-note
None
```
> docs: improve the display of docker-compose examples

- docs/developer-guide/plugin/basics/structure.md
- versioned_docs/version-2.20/developer-guide/plugin/basics/structure.md
更新插件项目结构文档
```release-note
None
```
> refactor: update plugin structure doc

- docs/developer-guide/plugin/basics/manifest.md
- versioned_docs/version-2.20/developer-guide/plugin/basics/manifest.md
更新插件描述文件的文档
```release-note
None
```
> refactor: update plugin manifest doc

- docs/developer-guide/plugin/basics/devtools.md
- versioned_docs/version-2.20/developer-guide/plugin/basics/devtools.md
更新 devtools 使用文档
```release-note
None
```
> docs: update devtools documents

- .github/workflows/node.js.yml
此 PR 解决了每个页面的“最后更新时间”和作者信息都相同，并且被设置为最近一次提交的时间和作者的问题。
它修改了用于发布站点的 docs 工作流中的 git fetch 深度，具体细节请参见此讨论： https://github.com/facebook/docusaurus/issues/2798#issuecomment-636602951
```release-note
None
```
> fix: show correct last update time/author

- docs/developer-guide/plugin/api-reference/server/notification.md
- docs/developer-guide/plugin/basics/server/object-management.md
- sidebars.js
- versioned_docs/version-2.20/developer-guide/plugin/api-reference/server/notification.md
- versioned_docs/version-2.20/developer-guide/plugin/basics/server/object-management.md
- versioned_sidebars/version-2.20-sidebars.json
新增通知功能相关开发文档
```release-note
None
```
> docs: add document for notification

- docs/developer-guide/plugin/security/rbac.md
- versioned_docs/version-2.20/developer-guide/plugin/security/rbac.md
修复聚合角色中错误的地方
```release-note
None
```
> fix: aggregate role docs

- docs/developer-guide/plugin/basics/devtools.md
- versioned_docs/version-2.20/developer-guide/plugin/basics/devtools.md
更新 Devtools 文档
```release-note
None
```
> refactor: update document for devtools

- docs/developer-guide/plugin/interaction/shared-events.md
- sidebars.js
- versioned_docs/version-2.20/developer-guide/plugin/interaction/shared-events.md
- versioned_sidebars/version-2.20-sidebars.json
添加共享事件文档
```release-note
None
```
> docs: add shared events document for developer

- babel.config.js
- package.json
- pnpm-lock.yaml
升级 Docusaurus 至 3.6.2，以修复开发环境无法启动的问题。
```release-note
None
```
> chore: bump docusaurus to 3.6.2

- docs/developer-guide/plugin/basics/server/object-management.md
- versioned_docs/version-2.20/developer-guide/plugin/basics/server/object-management.md
新增 SystemInfoGetter 共享 Bean 使用文档
```release-note
None
```
> docs: add docs for system info getter

- docs/developer-guide/theme/finder-apis/category.md
- docs/developer-guide/theme/finder-apis/contributor.md
- docs/developer-guide/theme/finder-apis/tag.md
- versioned_docs/version-2.16/developer-guide/theme/finder-apis/category.md
- versioned_docs/version-2.16/developer-guide/theme/finder-apis/contributor.md
- versioned_docs/version-2.16/developer-guide/theme/finder-apis/tag.md
- versioned_docs/version-2.17/developer-guide/theme/finder-apis/category.md
- versioned_docs/version-2.17/developer-guide/theme/finder-apis/contributor.md
- versioned_docs/version-2.17/developer-guide/theme/finder-apis/tag.md
- versioned_docs/version-2.18/developer-guide/theme/finder-apis/category.md
- versioned_docs/version-2.18/developer-guide/theme/finder-apis/contributor.md
- versioned_docs/version-2.18/developer-guide/theme/finder-apis/tag.md
- versioned_docs/version-2.19/developer-guide/theme/finder-apis/category.md
- versioned_docs/version-2.19/developer-guide/theme/finder-apis/contributor.md
- versioned_docs/version-2.19/developer-guide/theme/finder-apis/tag.md
- versioned_docs/version-2.20/developer-guide/theme/finder-apis/category.md
- versioned_docs/version-2.20/developer-guide/theme/finder-apis/contributor.md
- versioned_docs/version-2.20/developer-guide/theme/finder-apis/tag.md
修复 categoryFinder 和 tagFinder 关于 getByNames 的错误示例。
Fixes https://github.com/halo-dev/docs/issues/475
```release-note
None
```
> fix: correct getByNames method examples for category and tag api

- docs/getting-started/install/jar-file.md
- versioned_docs/version-2.17/getting-started/install/jar-file.md
- versioned_docs/version-2.18/getting-started/install/jar-file.md
- versioned_docs/version-2.19/getting-started/install/jar-file.md
- versioned_docs/version-2.20/getting-started/install/jar-file.md
移除 Jar 部署方式中配置示例的页面缓存配置，这个配置已经在 2.17+ 移除。
```release-note
None
```
> docs: remove page cache config for jar-file document

- package.json
- sidebars.js
- versioned_sidebars/version-2.20-sidebars.json
添加 Zeabur 平台的部署文档链接。
https://zeabur.com/docs/zh-CN/marketplace/halo
```release-note
None
```
> docs: add Zeabur platform deployment documentation link

- docs/getting-started/install/docker-compose.md
- docs/getting-started/install/jar-file.md
- docs/getting-started/install/slots/_docker-args.md
- versioned_docs/version-2.21/getting-started/install/docker-compose.md
- versioned_docs/version-2.21/getting-started/install/jar-file.md
- versioned_docs/version-2.21/getting-started/install/slots/_docker-args.md
> Highlight PostgreSQL as recommended database in docs

- docs/getting-started/install/cloud/alibaba-cloud-market.md
- versioned_docs/version-2.21/getting-started/install/cloud/alibaba-cloud-market.md
移除 1Panel 相关内容，因为阿里云云市场中的镜像没有使用 1Panel 进行部署。
```release-note
None
```
> docs: remove 1panel related content in alibaba-cloud-market
