halo-dev/docs

docs/developer-guide/core/prepare.md

Refactor the way of project clone

---

docusaurus.config.js
i18n/zh-Hans/code.json
i18n/zh-Hans/docusaurus-plugin-content-docs/version-1.4.15.json
i18n/zh-Hans/docusaurus-plugin-content-docs/version-1.4.16.json
i18n/zh-Hans/docusaurus-theme-classic/footer.json

chore: update copyright to fit2cloud

---

package.json
pnpm-lock.yaml

https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.14

chore(deps): upgrade docusaurus to beta.14

---

docs/intro.md
versioned_docs/version-1.4.17/intro.md

docs: add demo site

---

docs/developer-guide/core/code-style.md

Add step of choosing checkstyle version. See [here](https://github.com/halo-dev/halo/blob/2249ef1103f6716ac88ea045a1b28549890da6cf/build.gradle#L13) for more.
Fix #29

Add step of choosing checkstyle version

---

docs/getting-started/install/third-party.md
versioned_docs/version-1.4.17/getting-started/install/third-party.md

fix: error links in the three-party installation tutorial

---

docs/developer-guide/theme/template-tag.md
versioned_docs/version-1.4.17/developer-guide/theme/template-tag.md

docs: add the way to get the category tree in the theme development documentation

---

docs/developer-guide/theme/page-variable.md

fix: typo in page-variable.md

---

docusaurus.config.js

修复因错误配置导致 Google Analytics 无法统计的问题。
see https://github.com/facebook/docusaurus/pull/5832

fix: google analytics settings

---

docs/getting-started/install/docker.md
docs/getting-started/install/linux.md
docs/getting-started/install/other/docker-mysql.md
docs/getting-started/upgrade.md

docs: update download link for halo 1.5 alpha

---

i18n/zh-Hans/code.json
package.json
pnpm-lock.yaml

see https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.17

chore: bump docusaurus to beta 17

---

docs/getting-started/config.md
docs/getting-started/install/third-party.md

Add redis configuration documents

Add redis configuration documents

---

docs/getting-started/install/docker.md
docs/getting-started/install/linux.md
docs/getting-started/install/other/docker-mysql.md
docs/getting-started/upgrade.md

doc: update documents for Halo 1.5

---

docs/intro.md
versioned_docs/version-1.5.0/intro.md

doc: update intro.md

---

.github/workflows/node.js.yml

添加 markdown lint 的 GitHub Action 检测。

chore: actions add check step

---

docs/getting-started/install/docker.md
docs/getting-started/install/linux.md
docs/getting-started/install/other/docker-compose.md
docs/getting-started/install/other/docker-mysql.md
docs/getting-started/upgrade.md
docs/intro.md

docs: update documentations for Halo 1.5.2

---

docs/getting-started/install/other/tencent-cloudbase.md

处理代码可能会拉不下来的情况，请求一直超时导致部署失败。添加一个额外的按钮，来源为Gitee地址
before:
after:

Add gitee source button in Tencent cloud deployment

---

docs/getting-started/install/docker.md
docs/getting-started/install/linux.md
docs/getting-started/install/other/docker-compose.md
docs/getting-started/install/other/docker-mysql.md
docs/getting-started/upgrade.md
docs/intro.md

docs: update documentations for Halo 1.5.3

---

docs/developer-guide/theme/template-tag.md
versioned_docs/version-1.5.4/developer-guide/theme/template-tag.md

Fixes #85 
```release-note
None
```

fix: photoTag listByTeam example

---

docs/developer-guide/theme/template-tag.md
versioned_docs/version-1.5.4/developer-guide/theme/template-tag.md

methods:
* listTeams
* listTeamsByRandom
```release-note
None
```

fix: linkTag example

---

docs/getting-started/install/docker.md

添加 2.0 Alpha 的使用提示。
```release-note
None
```

docs: refine usage documentation of Halo 2.0

---

docs/intro.md

更新文档首页。
```release-note
None
```

docs: update intro

---

docs/getting-started/install/docker-compose.md
sidebars.js

/cc @halo-dev/sig-docs 
添加使用 Docker Compose 部署的文档。
```release-note
None
```

docs: add documentation of docker compose

---

docs/intro.md
versioned_docs/version-1.5.4/intro.md

提供 Halo 2.0 的在线演示环境。
```release-note
None
```

docs: provides Halo 2.0 online demo environment

---

docs/getting-started/install/docker-compose.md
docs/getting-started/install/docker.md
docs/intro.md
versioned_docs/version-1.5/getting-started/install/docker.md
versioned_docs/version-1.5/getting-started/install/linux.md
versioned_docs/version-1.5/getting-started/install/other/docker-compose.md
versioned_docs/version-1.5/getting-started/install/other/docker-mysql.md
versioned_docs/version-1.5/getting-started/upgrade.md
versioned_docs/version-1.5/intro.md
versioned_docs/version-1.6/getting-started/install/docker.md
versioned_docs/version-1.6/getting-started/install/linux.md
versioned_docs/version-1.6/getting-started/install/other/docker-compose.md
versioned_docs/version-1.6/getting-started/install/other/docker-mysql.md
versioned_docs/version-1.6/getting-started/upgrade.md
versioned_docs/version-1.6/intro.md

更新 Halo `1.6.0` `1.5.5` `2.0.0-alpha.2` 的版本号。
/cc @halo-dev/sig-docs  
```release-note
None
```

docs: update versions for `1.6.0` `1.5.5` `2.0.0-alpha.2`

---

docs/getting-started/install/docker-compose.md
docs/getting-started/install/docker.md
docs/intro.md

更新 2.0.0 alpha 的版本号。 https://github.com/halo-dev/halo/releases/tag/v2.0.0-alpha.3
```release-note
None
```

docs: update documentation for Halo 2.0.0-alpha.3

---

docs/getting-started/install/docker-compose.md

1. 移除 `/etc/timezone` 和 `/etc/localtime` 的挂载。
2. PostgreSQL 容器增加 `healthcheck`。
```release-note
None
```

docs: update documentation for docker-compose

---

docs/developer-guide/core/run.md
docs/getting-started/install/docker-compose.md
docs/getting-started/install/docker.md
docs/intro.md

为 Halo 2.0.0-beta.1 修改版本号。
```release-note
None
```

docs: update documentation for Halo 2.0.0-beta.1

---

docs/getting-started/install/docker-compose.md
docs/getting-started/install/docker.md
docs/intro.md

为 [Halo 2.0.0-beta.2](https://github.com/halo-dev/halo/releases/tag/v2.0.0-beta.2) 修改版本号。
```release-note
None
```

docs: update documentation for Halo 2.0.0-beta.2

---

package.json

Adapt lint script in Windows platform

---

docs/getting-started/install/docker-compose.md
docs/getting-started/install/docker.md
docs/getting-started/prepare.md
docs/user-guide/faq.md
versioned_docs/version-2.0/getting-started/install/docker-compose.md
versioned_docs/version-2.0/getting-started/install/docker.md
versioned_docs/version-2.0/getting-started/prepare.md
versioned_docs/version-2.0/user-guide/faq.md

在部署文档中添加安装 Docker 的提示。
```release-note
None
```

docs: add docker installation tips

---

docs/getting-started/install/docker-compose.md
docs/getting-started/install/docker.md
docs/intro.md
docs/user-guide/faq.md
docusaurus.config.js
i18n/zh-Hans/code.json
i18n/zh-Hans/docusaurus-plugin-content-docs/version-2.0.json
versioned_docs/version-2.0/getting-started/install/docker-compose.md
versioned_docs/version-2.0/getting-started/install/docker.md
versioned_docs/version-2.0/intro.md
versioned_docs/version-2.0/user-guide/faq.md

为 [Halo 2.0.1](https://github.com/halo-dev/halo/releases/tag/v2.0.1) 更新版本号。
```release-note
None
```

docs: update documentation for Halo 2.0.1

---

docs/intro.md
versioned_docs/version-2.0/intro.md

更新介绍文档中快速开始的命令，提供初始管理员账号和外部访问链接的环境变量设置。
```release-note
None
```

feat: improve the quick start section of the introduction

---

sidebars.js
versioned_sidebars/version-2.0-sidebars.json

在 PR #124 中误删了侧边栏的常见问题，现在重新添加回来。
```release-note
docs: recover FAQ in sidebar
```

docs: recover FAQ in sidebar

---

docs/developer-guide/core/build.md
docs/developer-guide/core/prepare.md
docs/developer-guide/core/run.md
sidebars.js
versioned_docs/version-2.0/developer-guide/core/build.md
versioned_docs/version-2.0/developer-guide/core/prepare.md
versioned_docs/version-2.0/developer-guide/core/run.md
versioned_sidebars/version-2.0-sidebars.json

提供自编译可执行 JAR 和 Docker 镜像的文档。
Fixes https://github.com/halo-dev/docs/issues/114
```release-note
None
```

docs: add documentation about compilation

---

docs/contribution/pr.md
versioned_docs/version-2.0/contribution/pr.md

更新 Pull Request 贡献指南。
Fixes https://github.com/halo-dev/docs/issues/146
```release-note
None
```

docs: update documentation for pull request contribution

---

docs/developer-guide/theme/vo/ListedPostVo.md
docs/developer-guide/theme/vo/ListedSinglePageVo.md
docs/developer-guide/theme/vo/PostVo.md
docs/developer-guide/theme/vo/SinglePageVo.md
versioned_docs/version-2.2/developer-guide/theme/vo/ListedPostVo.md
versioned_docs/version-2.2/developer-guide/theme/vo/ListedSinglePageVo.md
versioned_docs/version-2.2/developer-guide/theme/vo/PostVo.md
versioned_docs/version-2.2/developer-guide/theme/vo/SinglePageVo.md

为主题开发文档中关于文章和自定义页面的 VO 描述添加 lastModifyTime 字段。后端改动见：https://github.com/halo-dev/halo/pull/3101
Fixes #169 
```release-note
None
```

docs: add lastModifyTime field description for post and singlePage related vo

---

docs/getting-started/install/docker-compose.md
docs/getting-started/install/docker.md
versioned_docs/version-2.0/getting-started/install/docker-compose.md
versioned_docs/version-2.0/getting-started/install/docker.md
versioned_docs/version-2.1/getting-started/install/docker-compose.md
versioned_docs/version-2.1/getting-started/install/docker.md
versioned_docs/version-2.2/getting-started/install/docker-compose.md
versioned_docs/version-2.2/getting-started/install/docker.md

添加更新 Docker 镜像的文档。
Fixes #150 
```release-note
None
```

docs: add documentation for update docker image to upgrade halo

---

docs/developer-guide/theme/global-variables.md
docs/developer-guide/theme/vo/SiteSettingVo.md
docs/developer-guide/theme/vo/ThemeVo.md
sidebars.js
versioned_docs/version-2.0/developer-guide/theme/global-variables.md
versioned_docs/version-2.0/developer-guide/theme/vo/SiteSettingVo.md
versioned_docs/version-2.0/developer-guide/theme/vo/ThemeVo.md
versioned_docs/version-2.1/developer-guide/theme/global-variables.md
versioned_docs/version-2.1/developer-guide/theme/vo/SiteSettingVo.md
versioned_docs/version-2.1/developer-guide/theme/vo/ThemeVo.md
versioned_docs/version-2.2/developer-guide/theme/global-variables.md
versioned_docs/version-2.2/developer-guide/theme/vo/SiteSettingVo.md
versioned_docs/version-2.2/developer-guide/theme/vo/ThemeVo.md
versioned_sidebars/version-2.0-sidebars.json
versioned_sidebars/version-2.1-sidebars.json
versioned_sidebars/version-2.2-sidebars.json

添加 Halo 为模板引擎提供的全局变量的文档。
Fixes #161 
```release-note
None
```

docs: add documentation for template engine global variables

---

docs/getting-started/install/docker-compose.md
versioned_docs/version-2.1/getting-started/install/docker-compose.md
versioned_docs/version-2.2/getting-started/install/docker-compose.md

fix: nginx link error in docker-compose page

---

docs/developer-guide/core/build.md
versioned_docs/version-2.4/developer-guide/core/build.md

See https://github.com/halo-dev/docs/issues/205 for more.
```release-note
None
```

Update document about building halo 2.4.0

---

docs/getting-started/install/docker-compose.md
docs/getting-started/install/docker.md
docs/getting-started/install/other/traefik.md
docs/user-guide/faq.md
versioned_docs/version-2.4/getting-started/install/docker-compose.md
versioned_docs/version-2.4/getting-started/install/docker.md
versioned_docs/version-2.4/getting-started/install/other/traefik.md
versioned_docs/version-2.4/user-guide/faq.md

为 Halo 2.4.1 更新文档。
```release-note
None
```

docs: update documentation for Halo 2.4.1

---

docs/getting-started/migrate-from-1.x.md
versioned_docs/version-2.4/getting-started/migrate-from-1.x.md

更新迁移文档。目前 Halo 的官方迁移插件已经基本实现所有数据的迁移，请看：
- https://github.com/halo-sigs/plugin-migrate/pull/19
- https://github.com/halo-sigs/plugin-migrate/pull/21
Fixes #208 
```release-note
None
```

docs: update migration documentation

---

docs/getting-started/install/docker-compose.md
docs/getting-started/install/docker.md
docs/getting-started/install/slots/docker-args.md
versioned_docs/version-2.5/getting-started/install/docker-compose.md
versioned_docs/version-2.5/getting-started/install/docker.md
versioned_docs/version-2.5/getting-started/install/slots/docker-args.md

优化安装文档。
1. 优化安装完成之后的提示。
2. 优化 Docker 启动参数的描述。
3. Docker 的数据库配置参数添加 MariaDB 的说明。
4. 移动反向代理方式的顺序。
```release-note
None 
```

docs: refine documentation of installation

---

docs/developer-guide/plugin/runtime-mode.md
versioned_docs/version-2.5/developer-guide/plugin/runtime-mode.md

Closes #220
```release-note
None
```

docs: fix incorrect configuration instructions in runtime-mode.md

---

docs/developer-guide/form-schema.md
versioned_docs/version-2.5/developer-guide/form-schema.md

更新 Form Schema 文档中 Attachment 类型的参数。
Ref https://github.com/halo-dev/halo/pull/3827
```release-note
None
```

docs: update documentation of attachment form schema

---

package.json
pnpm-lock.yaml

升级 Docusaurus 的版本至 2.4 
```release-note
None
```

chore: bump docusaurus version to 2.4

---

docs/developer-guide/form-schema.md
versioned_docs/version-2.6/developer-guide/form-schema.md

完善开发者文档中关于 Repeater 表单项的参数。
```release-note
None
```

docs: refine repeater props

---

docs/getting-started/install/other/nginxproxymanager.md
sidebars.js
versioned_docs/version-2.0/getting-started/install/other/nginxproxymanager.md
versioned_docs/version-2.1/getting-started/install/other/nginxproxymanager.md
versioned_docs/version-2.2/getting-started/install/other/nginxproxymanager.md
versioned_docs/version-2.3/getting-started/install/other/nginxproxymanager.md
versioned_docs/version-2.4/getting-started/install/other/nginxproxymanager.md
versioned_docs/version-2.5/getting-started/install/other/nginxproxymanager.md
versioned_docs/version-2.6/getting-started/install/other/nginxproxymanager.md
versioned_sidebars/version-2.6-sidebars.json

修复 nginxproxymanager.md 文档中标题级别与其他文档不一致的问题。
```release-note
None
```

docs: fix headings of nginxproxymanager.md

---

docs/getting-started/install/helm.md
sidebars.js
versioned_docs/version-2.6/getting-started/install/helm.md
versioned_sidebars/version-2.6-sidebars.json

增加 Helm Chart 部署文档。
Close #181

docs: 增加 Helm 部署文档

---

docusaurus.config.js
package.json
pnpm-lock.yaml
src/css/custom.css

支持点击放大图片。
```release-note
None 
```

feat: add image zoom feature

---

docs/developer-guide/theme/vo/ContributorVo.md

link: https://github.com/halo-dev/halo/pull/4705
```release-note
更新 ContributorVo 格式
```

docs: update ContributorVo (halo-dev/halo#4705)

---

.github/workflows/node.js.yml

重新添加 ssh-deploy 的 action 步骤，用于部署到服务器。
```release-note
None
```

chore: add ssh deploy step

---

.github/workflows/node.js.yml

在执行 ssh deploy 操作前，压缩构建产物。
```release-note
None
```

chore: zip dist files before ssh deploy

---

docs/developer-guide/core/run.md
versioned_docs/version-2.10/developer-guide/core/run.md

为开发环境运行文档添加下载预设插件的步骤。
```release-note
None
```

docs: add downloadPluginPresets step for development documentation

---

docs/getting-started/install/docker-compose.md
docs/getting-started/install/docker.md
versioned_docs/version-2.10/getting-started/install/docker-compose.md
versioned_docs/version-2.10/getting-started/install/docker.md

优化使用 H2 数据库的提示。
```release-note
None
```

docs: refine h2 database tips

---

docs/user-guide/faq.md
versioned_docs/version-2.11/user-guide/faq.md

Close #282
```release-note
None
```

docs: 更新FAQ中的忘记密码处理方式

---

docs/developer-guide/core/build.md
docs/developer-guide/core/run.md

This PR mainly adapts PR <https://github.com/halo-dev/halo/pull/5314>.
```release-note
None
```

Refactor project build and run

---

docs/developer-guide/plugin/api-reference/server/extension.md

优化关于自定义 APIs 路由规则的描述文档
```release-note
None
```

doc: refine doc for route rules of custom extension apis

---

docs/developer-guide/core/code-style.md

addressing outdated version issue of Checkstyle in code style documentation

---

docs/getting-started/install/docker-compose.md
versioned_docs/version-2.13/getting-started/install/docker-compose.md

优化 Docker Compose 文件模板。
- 移除 container_name，适用于在服务器部署多个 Halo，防止容器名冲突。
- 默认移除数据库的端口映射并添加提示，根据反馈这可能造成一定的误导。
```release-note
None
```

docs: update sample of docker compose file

---

versioned_docs/version-2.13/getting-started/install/docker.md
versioned_docs/version-2.13/getting-started/install/podman.md
versioned_docs/version-2.13/intro.md

同时使用 `-it` 和 `-d`，`-d` 会覆盖 `-it`，容器将会在后台运行，而 `-it` 参数请求的交互式会话和伪终端不会生效。
```release-note
None
```

docs: delete unnecessary options

---

.github/workflows/node.js.yml

更新 GitHub Workflow，修复警告。
```release-note
None
```

chore: update workflow

---

docs/getting-started/prepare.md
versioned_docs/version-2.14/getting-started/prepare.md

更新《写在前面》。
- 更新网络要求说明
- 更新 Docker 依赖说明
- 更新 Jar 文件部署说明
- 更新数据库说明
- 更新浏览器支持说明
```release-note
None
```

docs: update prepare document

---

docs/developer-guide/theme/config.md
docs/developer-guide/theme/prepare.md
docs/developer-guide/theme/settings.md
versioned_docs/version-2.14/developer-guide/theme/config.md
versioned_docs/version-2.14/developer-guide/theme/prepare.md
versioned_docs/version-2.14/developer-guide/theme/settings.md

更新主题开发中的 theme.yaml 示例。
Ref https://github.com/halo-dev/halo/issues/5721
```release-note
None
```

docs: update example of theme manifest file

---

docs/developer-guide/plugin/basics/manifest.md
docs/developer-guide/plugin/examples/todolist.md
versioned_docs/version-2.14/developer-guide/plugin/basics/manifest.md
versioned_docs/version-2.14/developer-guide/plugin/examples/todolist.md

更新插件开发中的 plugin.yaml 示例。
Ref https://github.com/halo-dev/halo/issues/5721
```release-note
None
```

docs: update example of plugin manifest file

---

docs/developer-guide/plugin/api-reference/server/websocket.md
sidebars.js

See https://github.com/halo-dev/halo/pull/5662#issuecomment-2049166868 for more.
```release-note
None
```

Add documentation for websocket

---

docs/developer-guide/plugin/api-reference/server/reconciler.md
versioned_docs/version-2.12/developer-guide/plugin/api-reference/server/reconciler.md
versioned_docs/version-2.13/developer-guide/plugin/api-reference/server/reconciler.md
versioned_docs/version-2.14/developer-guide/plugin/api-reference/server/reconciler.md

condtions should be conditions? 🤔

Fix typo condtions to conditions

---

docs/developer-guide/plugin/basics/manifest.md
docs/developer-guide/plugin/examples/todolist.md
docs/developer-guide/theme/config.md
docs/developer-guide/theme/prepare.md
docs/developer-guide/theme/settings.md

为主题和插件的配置文件示例添加 issues 字段。
Ref https://github.com/halo-dev/halo/pull/5755
```release-note
None
```

docs: add issues field for theme and plugin manifest example

---

docs/developer-guide/plugin/api-reference/server/extension-points/template-head-processor.md
sidebars.js
versioned_docs/version-2.15/developer-guide/plugin/api-reference/server/extension-points/template-head-processor.md
versioned_sidebars/version-2.15-sidebars.json

添加 TemplateHeadProcessor 扩展点的文档
开源之夏已经开始报名，但是发现缺少此文档可能会对报名者造成困扰
```release-note
None
```

doc: add doc for template head processor extension point

---

versioned_docs/version-2.12/developer-guide/plugin/api-reference/server/role-template.md
versioned_docs/version-2.13/developer-guide/plugin/api-reference/server/role-template.md
versioned_docs/version-2.14/developer-guide/plugin/api-reference/server/role-template.md
versioned_docs/version-2.15/developer-guide/plugin/api-reference/server/role-template.md

修复权限控制文档中关于 Role 的 apiVersion 错误的问题
```release-note
None
```

fix: api version for role template

---

docs/developer-guide/plugin/api-reference/server/role-template.md
versioned_docs/version-2.15/developer-guide/plugin/api-reference/server/role-template.md

重写 API 权限控制的文档以减小用户理解成本
```release-note
None
```

refactor: role template docs

---

docs/developer-guide/core/run.md

```release-note
修改 UI 服务启动方式为直接从 pnpm 启动
```

feat: modify ui service startup way

---

docusaurus.config.js
package.json
pnpm-lock.yaml
src/theme/SearchBar.js

使用自建的 Meilisearch 作为文档搜索引擎，代替 Algolia。
```release-note
None
```

chore: use selfhosted-meilisearch as docs search engine

---

docs/developer-guide/plugin/examples/todolist.md

修改插件开发案例文档，来匹配最新的 [plugin-starter](https://github.com/halo-dev/plugin-starter)。
```release-note
None
```

docs: update document of plugin example

---

docs/developer-guide/theme/template-variables/archives.md
versioned_docs/version-2.15/developer-guide/theme/template-variables/archives.md

fix: total pages in archives.html sample

---

docs/developer-guide/plugin/api-reference/server/extension-points/additional-webfilter.md
docs/developer-guide/plugin/api-reference/server/role-template.md
docs/getting-started/install/other/nginxproxymanager.md
versioned_docs/version-2.10/getting-started/install/other/nginxproxymanager.md
versioned_docs/version-2.11/getting-started/install/other/nginxproxymanager.md
versioned_docs/version-2.12/developer-guide/plugin/api-reference/server/extension-points/additional-webfilter.md
versioned_docs/version-2.12/developer-guide/plugin/api-reference/server/role-template.md
versioned_docs/version-2.12/getting-started/install/other/nginxproxymanager.md
versioned_docs/version-2.13/developer-guide/plugin/api-reference/server/extension-points/additional-webfilter.md
versioned_docs/version-2.13/developer-guide/plugin/api-reference/server/role-template.md
versioned_docs/version-2.13/getting-started/install/other/nginxproxymanager.md
versioned_docs/version-2.14/developer-guide/plugin/api-reference/server/extension-points/additional-webfilter.md
versioned_docs/version-2.14/developer-guide/plugin/api-reference/server/role-template.md
versioned_docs/version-2.14/getting-started/install/other/nginxproxymanager.md
versioned_docs/version-2.15/developer-guide/plugin/api-reference/server/extension-points/additional-webfilter.md
versioned_docs/version-2.15/developer-guide/plugin/api-reference/server/role-template.md
versioned_docs/version-2.15/getting-started/install/other/nginxproxymanager.md

更新文案：登陆 -> 登录
```release-note
None
```

typo: 登陆 -> 登录

---

docs/developer-guide/plugin/basics/ui/entry.md
versioned_docs/version-2.12/developer-guide/plugin/basics/ui/entry.md
versioned_docs/version-2.13/developer-guide/plugin/basics/ui/entry.md
versioned_docs/version-2.14/developer-guide/plugin/basics/ui/entry.md
versioned_docs/version-2.15/developer-guide/plugin/basics/ui/entry.md

修复异常链接。
```release-note
None
```

fix: broken links

---

.github/workflows/node.js.yml
pnpm-lock.yaml

升级 pnpm 版本。
```release-note
None
```

chore: bump pnpm version to 9

---

docs/getting-started/install/docker-compose.md
docs/getting-started/install/docker.md
docs/getting-started/install/jar-file.md
docs/getting-started/install/other/traefik.md
docs/getting-started/install/podman.md
docs/getting-started/install/slots/_docker-registry-list.md
docs/user-guide/faq.md
versioned_docs/version-2.16/getting-started/install/docker-compose.md
versioned_docs/version-2.16/getting-started/install/docker.md
versioned_docs/version-2.16/getting-started/install/jar-file.md
versioned_docs/version-2.16/getting-started/install/other/traefik.md
versioned_docs/version-2.16/getting-started/install/podman.md
versioned_docs/version-2.16/getting-started/install/slots/_docker-registry-list.md
versioned_docs/version-2.16/user-guide/faq.md

更新部署文档，添加我们的自建 Docker 仓库，并设置为首选。
```release-note
None
```

docs: update default docker registry

---

docs/developer-guide/core/prepare.md
versioned_docs/version-2.16/developer-guide/core/prepare.md

docs: update pnpm version require

---

docs/developer-guide/plugin/api-reference/server/extension-client.md
versioned_docs/version-2.17/developer-guide/plugin/api-reference/server/extension-client.md

添加 ListOptions builder 的文档说明
see also https://github.com/halo-dev/halo/pull/6148
```release-note
None
```

docs: add docs for list options builder

---

docs/developer-guide/theme/finder-apis/plugin.md
versioned_docs/version-2.17/developer-guide/theme/finder-apis/plugin.md

添加插件 Finder API 中通过插件名称和版本判断某插件是否可用的 API 的文档
see also https://github.com/halo-dev/halo/pull/6236
```release-note
None
```

docs: add docs for check plugin availability by version

---

docs/getting-started/install/cloud/tencent-cloud-lighthouse.md
versioned_docs/version-2.17/getting-started/install/cloud/tencent-cloud-lighthouse.md

docs: update tencent-cloud-lighthouse.md

---

docs/contribution/sponsor.md
docs/intro.md
versioned_docs/version-2.10/contribution/sponsor.md
versioned_docs/version-2.10/intro.md
versioned_docs/version-2.11/contribution/sponsor.md
versioned_docs/version-2.11/intro.md
versioned_docs/version-2.12/contribution/sponsor.md
versioned_docs/version-2.12/intro.md
versioned_docs/version-2.13/contribution/sponsor.md
versioned_docs/version-2.13/intro.md
versioned_docs/version-2.14/contribution/sponsor.md
versioned_docs/version-2.14/intro.md
versioned_docs/version-2.15/contribution/sponsor.md
versioned_docs/version-2.15/intro.md
versioned_docs/version-2.16/contribution/sponsor.md
versioned_docs/version-2.16/intro.md
versioned_docs/version-2.17/contribution/sponsor.md
versioned_docs/version-2.17/intro.md
versioned_docs/version-2.18/contribution/sponsor.md
versioned_docs/version-2.18/intro.md

/kind cleanup
更新爱发电的地址。
```release-note
None
```

chore: update afdian url

---

docs/getting-started/install/docker-compose.md
versioned_docs/version-2.18/getting-started/install/docker-compose.md

Fixes #397 
```release-note
修复错误格式的 External URL 配置
```

Rectify the invalid external URL

---

docs/developer-guide/form-schema.md

添加 formkit select 组件的文档
```release-note
None
```

docs: add formkit select component

---

docs/developer-guide/form-schema.md

更新 formkit select  组件关于远程加载时的字段
```release-note
None
```

docs: update select field selector  document

---

docs/developer-guide/form-schema.md
versioned_docs/version-2.19/developer-guide/form-schema.md

补充 formkit select 相关文档。
Fixes #408 
```release-note
None
```

docs: supplement formkit select document

---

docs/developer-guide/theme/finder-apis/post.md
versioned_docs/version-2.19/developer-guide/theme/finder-apis/post.md

为 https://github.com/halo-dev/halo/pull/6531 补充文档说明
```release-note
None
```

docs: add docs for unified parameter list method of post finder

---

docs/developer-guide/form-schema.md

添加关于 menuSelect 输入类型的文档。
See https://github.com/halo-dev/halo/pull/6642
```release-note
None
```

docs: add documentation for menu select form item

---

docs/getting-started/install/cloud/alibaba-cloud-computenest.md
versioned_docs/version-2.19/getting-started/install/cloud/alibaba-cloud-computenest.md

docs: update alibaba-cloud-computenest deploy url

---

docs/developer-guide/plugin/basics/devtools.md
versioned_docs/version-2.20/developer-guide/plugin/basics/devtools.md

添加 Devtools 升级到 0.2.0 版本的升级提示
```release-note
None
```

docs: add devtools upgrade guide for 0.2.0

---

docs/developer-guide/restful-api/introduction.md
versioned_docs/version-2.20/developer-guide/restful-api/introduction.md

更新关于 Basic Auth 认证的说明。
```release-note
None
```

docs: update basic authentication documentation

---

docs/getting-started/install/docker-compose.md
docs/getting-started/install/docker.md
versioned_docs/version-2.20/getting-started/install/docker-compose.md
versioned_docs/version-2.20/getting-started/install/docker.md

为 Docker 部署添加 JVM_OPTS 环境变量的说明。
Fixes #17 
```release-note
None
```

docs: add JVM_OPTS environment documentation

---

docs/intro.md
versioned_docs/version-2.20/intro.md

更新介绍文档。
```release-note
None
```

docs: update intro documentation

---

docs/getting-started/install/docker-compose.md
docs/getting-started/install/jar-file.md
docusaurus.config.js
versioned_docs/version-2.20/getting-started/install/docker-compose.md
versioned_docs/version-2.20/getting-started/install/jar-file.md

添加创建数据库的提示。
Fixes https://github.com/halo-dev/docs/issues/336
```release-note
None
```

docs: add database creation tips

---

docs/developer-guide/annotations-form.md
docs/developer-guide/plugin/api-reference/server/extension-client.md
docs/developer-guide/plugin/api-reference/server/extension.md
docs/developer-guide/plugin/basics/devtools.md
docs/developer-guide/plugin/security/role-template.md
versioned_docs/version-2.20/developer-guide/annotations-form.md
versioned_docs/version-2.20/developer-guide/plugin/api-reference/server/extension-client.md
versioned_docs/version-2.20/developer-guide/plugin/api-reference/server/extension.md
versioned_docs/version-2.20/developer-guide/plugin/basics/devtools.md
versioned_docs/version-2.20/developer-guide/plugin/security/role-template.md

重写自定义模型的开发文档
```release-note
None
```

docs: rewrite extension development documentation

---

docusaurus.config.js
package.json
pnpm-lock.yaml

添加对 Mermaid Diagrams 的支持
```release-note
None
```

feat: diagrams can be rendered using Mermaid in a code block

---

docs/developer-guide/plugin/security/rbac.md
versioned_docs/version-2.20/developer-guide/plugin/security/rbac.md

typo: resrouces to resources

---

docs/developer-guide/plugin/interaction/dependency.md
docs/developer-guide/plugin/publish.md
sidebars.js
versioned_docs/version-2.20/developer-guide/plugin/interaction/dependency.md
versioned_docs/version-2.20/developer-guide/plugin/publish.md
versioned_sidebars/version-2.20-sidebars.json

新增插件依赖开发文档
```release-note
None
```

docs: add plugin dependencies docs

---

docs/developer-guide/plugin/interaction/making-plugin-extensible.md
sidebars.js
versioned_docs/version-2.20/developer-guide/plugin/interaction/making-plugin-extensible.md
versioned_sidebars/version-2.20-sidebars.json

提供插件如何被扩展的文档
```release-note
None
```

docs: add doc on defining and declaring extension points for plugin extensibility

---

docs/developer-guide/theme/vo/_UserVo.md
versioned_docs/version-2.16/developer-guide/theme/vo/_UserVo.md
versioned_docs/version-2.17/developer-guide/theme/vo/_UserVo.md
versioned_docs/version-2.18/developer-guide/theme/vo/_UserVo.md
versioned_docs/version-2.19/developer-guide/theme/vo/_UserVo.md
versioned_docs/version-2.20/developer-guide/theme/vo/_UserVo.md

移除 UserVo 类型示例中的 lastLoginAt 字段，目前这个字段并没有使用。
```release-note
None
```

docs: remove lastLoginAt field from UserVo

---

docs/developer-guide/plugin/extension-points/ui/interface/ListedPost.md
docs/developer-guide/theme/vo/_CategoryTreeVo.md
docs/developer-guide/theme/vo/_CategoryVo.md
docs/developer-guide/theme/vo/_TagVo.md
versioned_docs/version-2.16/developer-guide/plugin/api-reference/ui/extension-points/interface/ListedPost.md
versioned_docs/version-2.16/developer-guide/theme/vo/_CategoryTreeVo.md
versioned_docs/version-2.16/developer-guide/theme/vo/_CategoryVo.md
versioned_docs/version-2.16/developer-guide/theme/vo/_TagVo.md
versioned_docs/version-2.17/developer-guide/plugin/api-reference/ui/extension-points/interface/ListedPost.md
versioned_docs/version-2.17/developer-guide/theme/vo/_CategoryTreeVo.md
versioned_docs/version-2.17/developer-guide/theme/vo/_CategoryVo.md
versioned_docs/version-2.17/developer-guide/theme/vo/_TagVo.md
versioned_docs/version-2.18/developer-guide/plugin/api-reference/ui/extension-points/interface/ListedPost.md
versioned_docs/version-2.18/developer-guide/theme/vo/_CategoryTreeVo.md
versioned_docs/version-2.18/developer-guide/theme/vo/_CategoryVo.md
versioned_docs/version-2.18/developer-guide/theme/vo/_TagVo.md
versioned_docs/version-2.19/developer-guide/plugin/api-reference/ui/extension-points/interface/ListedPost.md
versioned_docs/version-2.19/developer-guide/theme/vo/_CategoryTreeVo.md
versioned_docs/version-2.19/developer-guide/theme/vo/_CategoryVo.md
versioned_docs/version-2.19/developer-guide/theme/vo/_TagVo.md
versioned_docs/version-2.20/developer-guide/plugin/extension-points/ui/interface/ListedPost.md
versioned_docs/version-2.20/developer-guide/theme/vo/_CategoryTreeVo.md
versioned_docs/version-2.20/developer-guide/theme/vo/_CategoryVo.md
versioned_docs/version-2.20/developer-guide/theme/vo/_TagVo.md

统一分类和标签的文章数量字段。
See https://github.com/halo-dev/halo/issues/7095
```release-note
None
```

docs: update postCount field in category vo and tag vo

---

versioned_docs/version-2.20/developer-guide/annotations-form.md

fix: error link syntax in annotations-form.md

---

docs/developer-guide/plugin/interaction/dependency.md
versioned_docs/version-2.20/developer-guide/plugin/interaction/dependency.md

更新插件 api 模块的 build.gradle 增加源码 JAR 配置文档以便让其他依赖者能获取到源码和文档便于开发
```release-note
None
```

chore: update the build.gradle file for the dependent plugin api module

---

docusaurus.config.js

As title
```release-note
None
```

chore: add rybbit tracking script

---

docusaurus.config.js

As title
```release-note
None
```

chore: remove umami tracking script

---

sidebars.js
versioned_sidebars/version-2.20-sidebars.json

docs: add Rainbond button

---

.github/workflows/node.js.yml
docusaurus.config.js
package.json
pnpm-lock.yaml
pnpm-workspace.yaml

Bump docusaurus to [3.8](https://github.com/facebook/docusaurus/releases/tag/v3.8.0)
```release-note
None
```

chore: bump docusaurus to 3.8

---

docs/developer-guide/plugin/interaction/shared-events.md
versioned_docs/version-2.20/developer-guide/plugin/interaction/shared-events.md

```release-note
补充用户登录和登出事件文档
```

docs: update document for UserLoginEvent and UserLogoutEvent

---

.editorconfig
docs/developer-guide/plugin/basics/ui/build.md
docs/developer-guide/plugin/basics/ui/entry.md
docs/developer-guide/plugin/basics/ui/intro.md
docs/developer-guide/plugin/publish.md
docusaurus.config.js
sidebars.js
versioned_docs/version-2.21/developer-guide/plugin/basics/ui/build.md
versioned_docs/version-2.21/developer-guide/plugin/basics/ui/entry.md
versioned_docs/version-2.21/developer-guide/plugin/basics/ui/intro.md
versioned_docs/version-2.21/developer-guide/plugin/publish.md
versioned_sidebars/version-2.21-sidebars.json

完善插件开发文档：
1. 更新 Workflow 配置示例。
2. 提供 UI 构建配置的说明文档。
```release-note
None
```

chore: refine plugin development documentation 
